services:
  # Servicio para el Frontend (Sitio Est√°tico)
  - type: web
    name: frontend
    env: static
    rootDir: frontend
    build_command: npm install && npm run build
    static_publish_path: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Servicio para el Backend (API con FastAPI)
  - type: web
    name: backend
    env: python
    rootDir: backend
    build_command: pip install -r requirements.txt
    start_command: uvicorn main:app --host 0.0.0.0 --port 10000
