services:
  # Servicio para el Frontend (Sitio Est√°tico)
  - type: web
    name: frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Servicio para el Backend (API con FastAPI)
  - type: web
    name: backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
